### ISSUE TITLE
Crear issues

### ISSUE THREAD

**Issue by damiancastelao** [Sr-fer/Proyecto-3nR#1]
Muy bien! ya tenéis los proyectos creados.
Ahora es el momento de empezar a crear issues, que son las tareas para empezar a darle forma al aplicación.
¿Cómo empezamos? Cual es la primera tarea.
Abrir un issue con esta primera tarea, y logicamente cerrar este issue.

**Comment by damiancastelao** [comment]
Quien es el encargado? Y la label? Completar esos datos

**Comment by damiancastelao** [comment]
Que pasó con la columna TODO de vuestro proyecto? Siguen faltando los atributos en este issue

**Comment by Sr-fer** [comment]
Este Issue ya está cerrado, y la columna To Do ya está
