### ISSUE TITLE
Base de la página

### ISSUE THREAD

**Issue by Sr-fer** [Sr-fer/Proyecto-3nR#3]
Que la página web tenga la estructura de 3x3 rectángulos, con sus respectivos espacios y encabezado, donde en estos rectángulos se dividan con las reglas del juego, en el medio el tablero y un último cuadro que contenga curiosidad y la historia del juego para que sea más completo. Cerrar ese Issue cuando esté la estructura sin los datos que contiene cada rectángulo para empezar con la estructura de la página. Esta tiene que ser responsive

**Comment by damiancastelao** [comment]
Esto es muy abstracto, ¿cual es la tarea? Pensar que un commit tiene que cerrar este issue

**Comment by Sr-fer** [comment]
Listo!
