### ISSUE TITLE
Estructura del JS

### ISSUE THREAD

**Issue by abranosrodriguez** [Sr-fer/Proyecto-3nR#5]
Tener los archivos JS correspondientes al juego. 
Para que pueda permitir jugar correctamente

**Comment by damiancastelao** [comment]
Que significa 'tener los archivos'. Concreta un poco mas para saber cuando se puede cerrar el issue

**Comment by abranosrodriguez** [comment]
Tener el archivo main.js donde estará la información necesaria con los archivos js restantes, para que el main no quede muy cargado.
Ya que puede tener un documeto js distinto o varios que vayan con el main.
